# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Ellmoe' do
  # Pods for Ellmoe
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    # 'DevSupport',
    # 'RCTActionSheet',
    # 'RCTAnimation',
    # 'RCTGeolocation',
    'RCTImage',
    # 'RCTLinkingIOS',
    # 'RCTNetwork',
    # 'RCTSettings',
    # 'RCTText',
    # 'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # pod 'DoubleConversion',
  #   :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
  #   :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Database', '~> 6.3.0'
  pod 'Firebase/Functions', '~> 6.3.0'
  pod 'Firebase/DynamicLinks', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/RemoteConfig', '~> 6.3.0'
  pod 'Firebase/Storage', '~> 6.3.0'
  pod 'Firebase/Performance', '~> 6.3.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.2'

  pod 'GoogleMaps'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  # react-native-maps dependencies
  # pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  # pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  # pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'


  pod 'react-native-exif', :path => '../node_modules/react-native-exif'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    # if target.name == "yoga"
    #   target.remove_from_project
    # end
    # if target.name = "cameraroll"
    #   target.remove_from_project
    # end
  end
end
#
# target 'Ellmoe-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
#
#   # Pods for Ellmoe-tvOS
#
#   target 'Ellmoe-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
